=== gentics/cms-oss/cms-core/src/main/java/com/gentics/contentnode/validation/map/policy-map.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="policyMap" type="policyMapModel"/>

  <xs:complexType name="node" abstract="true">
    <xs:complexContent>
      <xs:extension base="nodeModel">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="nodeModel">
    <xs:all>
      <xs:element name="default" type="policyRef" minOccurs="0"/>
      <xs:element name="fileDescription" type="policyRef" minOccurs="0"/>
      <xs:element name="fileName" type="policyRef" minOccurs="0"/>
      <xs:element name="folderDescription" type="policyRef" minOccurs="0"/>
      <xs:element name="folderName" type="policyRef" minOccurs="0"/>
      <xs:element name="mimeType" type="policyRef" minOccurs="0"/>
      <xs:element name="pageDescription" type="policyRef" minOccurs="0"/>
      <xs:element name="pageLanguage" type="policyRef" minOccurs="0"/>
      <xs:element name="pageName" type="policyRef" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="policyRef">
    <xs:complexContent>
      <xs:extension base="xmlRef">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="xmlRef" abstract="true">
    <xs:sequence/>
    <xs:attribute name="ref" type="xs:IDREF" use="required"/>
  </xs:complexType>

  <xs:complexType name="partType">
    <xs:complexContent>
      <xs:extension base="partTypeModel">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="partTypeModel">
    <xs:complexContent>
      <xs:extension base="policyGroupRef">
        <xs:sequence/>
        <xs:attribute name="typeId" type="xs:int" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="policyGroupRef">
    <xs:complexContent>
      <xs:extension base="xmlRef">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="policyMap" abstract="true">
    <xs:complexContent>
      <xs:extension base="policyMapModel">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="policyMapModel">
    <xs:sequence>
      <xs:element name="inputChannels" type="inputChannels"/>
      <xs:element name="policyGroups">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="policyGroup" type="policyGroup" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="policies">
        <xs:complexType>
          <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
              <xs:element name="antiSamy" type="antiSamyPolicy"/>
              <xs:element name="attribute" type="attributePolicy"/>
              <xs:element name="passThrough" type="passThroughPolicy"/>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="inputChannels">
    <xs:sequence>
      <xs:element name="contentAdmin" type="contentAdminWrapper"/>
      <xs:element name="nodes" type="nodeWrapper"/>
      <xs:element name="default" type="policyRef" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="contentAdminWrapper">
    <xs:all>
      <xs:element name="bundleDescription" type="policyRef" minOccurs="0"/>
      <xs:element name="bundleName" type="policyRef" minOccurs="0"/>
      <xs:element name="bundleSecret" type="policyRef" minOccurs="0"/>
      <xs:element name="fsPath" type="policyRef" minOccurs="0"/>
      <xs:element name="groupDescription" type="policyRef" minOccurs="0"/>
      <xs:element name="groupName" type="policyRef" minOccurs="0"/>
      <xs:element name="hostName" type="policyRef" minOccurs="0"/>
      <xs:element name="nodeDescription" type="policyRef" minOccurs="0"/>
      <xs:element name="nodeName" type="policyRef" minOccurs="0"/>
      <xs:element name="partTypes" type="partTypesWrapper"/>
      <xs:element name="roleDescription" type="policyRef" minOccurs="0"/>
      <xs:element name="roleName" type="policyRef" minOccurs="0"/>
      <xs:element name="userDescription" type="policyRef" minOccurs="0"/>
      <xs:element name="userEmail" type="policyRef" minOccurs="0"/>
      <xs:element name="userFirstLastName" type="policyRef" minOccurs="0"/>
      <xs:element name="userMessage" type="policyRef" minOccurs="0"/>
      <xs:element name="userName" type="policyRef" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="partTypesWrapper">
    <xs:sequence>
      <xs:element name="partType" type="partType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="default" type="policyGroupRef" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="nodeWrapper">
    <xs:sequence>
      <xs:element name="node" type="identifiedNode" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="default" type="nodeImpl"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="identifiedNode">
    <xs:complexContent>
      <xs:extension base="nodeImpl">
        <xs:sequence/>
        <xs:attribute name="localId" type="xs:int" use="required"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="nodeImpl">
    <xs:complexContent>
      <xs:extension base="node">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="policyGroup">
    <xs:complexContent>
      <xs:extension base="policyGroupModel">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="policyGroupModel">
    <xs:sequence>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element name="policy" type="policyRef"/>
        <xs:element name="default" type="defaultPolicyRef"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>
  </xs:complexType>

  <xs:complexType name="defaultPolicyRef">
    <xs:complexContent>
      <xs:extension base="policyRef">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="antiSamyPolicy">
    <xs:complexContent>
      <xs:extension base="policy">
        <xs:sequence/>
        <xs:attribute name="policyFile" type="xs:string"/>
        <xs:attribute name="domMode" type="xs:boolean"/>
        <xs:attribute name="outerElement" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="policy" abstract="true">
    <xs:complexContent>
      <xs:extension base="policyModel">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="policyModel">
    <xs:sequence/>
    <xs:attribute name="convertNodeTags" type="xs:boolean"/>
    <xs:attribute name="displayName" type="xs:string"/>
    <xs:attribute name="id" type="xs:ID" use="required"/>
    <xs:attribute name="uri" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="attributePolicy">
    <xs:complexContent>
      <xs:extension base="antiSamyPolicy">
        <xs:sequence>
          <xs:element name="occursIn" type="occursIn"/>
        </xs:sequence>
        <xs:attribute name="ignoreNodeTags" type="xs:boolean"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="occursIn">
    <xs:sequence/>
    <xs:attribute name="element" type="xs:string" use="required"/>
    <xs:attribute name="attribute" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="passThroughPolicy">
    <xs:complexContent>
      <xs:extension base="policy">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:simpleType name="policies">
    <xs:restriction base="xs:string">
      <xs:enumeration value="PARANOID_POLICY"/>
      <xs:enumeration value="ANY_URI_POLICY"/>
      <xs:enumeration value="ANY_CONTENT_POLICY"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== gentics/cms-oss/cms-oss-doc/src/main/assets/gcn_files/policy-map.custom.xml
<!--
	** Important Note **
	
	If any changes to the policies defined in the custom policy-map
	are made (in the policies section), the policy URI must be changed
	to a customer specific URI. Otherwise, there may be problems with
	Import/Export.
-->
<policyMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="policy-map.xsd">
	<!--
		inputChannels map a channel through which data is being input
		into the system, to either a policy or policy-group (specified
		in the policy and policy-group sections).
	 -->
	<inputChannels>
		<contentAdmin>
			<!--
				Since the policy for part-types is configurable, they must
				refer to a policy-group and not directly to a policy. The
				policy-group specifies a number of policies that may be
				configured for a part-type.
			-->
			<partTypes>
				<partType typeId="03" ref="AntiSamyDefault"/> <!-- HTML -->
				<partType typeId="21" ref="AntiSamyDefault"/> <!-- HTML (long) -->
			
				<!-- 
					URL part-types should only contain URIs. Never mixed content.
				-->
				<partType typeId="04" ref="AnyURI"/>   <!-- URL (page) -->
				<partType typeId="06" ref="AnyURI"/>   <!-- URL (image) -->
				<partType typeId="08" ref="AnyURI"/>   <!-- URL (file) -->
				<partType typeId="25" ref="AnyURI"/>   <!-- URL (folder) -->

				<!--
					We allow mixed content by default since implementers have to
					be aware of the danger of using custom node tags
					in attributes. Editors will not be able to use node tags in
					attributes (unless a policy is configured that allows such
					usage, e.g. with the ignoreNodeTags option).
				-->
				<default ref="AntiSamyDefault"/>
			</partTypes>
		</contentAdmin>
		<nodes>
			<!--
				Policies for inputs associated with a node may be defined:
				<node localId="...">...</node>
			-->
			<!--
				The default configuration will be used, if no node-specific
				configuration exists.
			-->
			<default>
				<!--
					Example configuration for inputs associated with a
					particular node: 
					<folderDescription ref="AntiSamyDefault"/>
					<folderName        ref="AntiSamyDefault"/>
				-->
				<!--
					Node default policy - for all inputs associated with a
					node that don't have a policy configuration.
				-->
		  		<default ref="antiSamy"/>
			</default>
		</nodes>
		<!--
			Global default policy - for all inputs that don't have a policy
			configuration.
		-->
		<default ref="antiSamy"/>
	</inputChannels>
    <policyGroups>
		<!--
			Groups of policies. This is for configurable input channels.
			When displaying a tag-part definition of a tag-type, there,
			one can find a drop-down which reflects one of these groups.
			The <default> policy in each group will be used as the effective
			policy if none is configured by the user.
		-->
		<policyGroup id="AnyURI">
		    <policy ref="antiSamy"/>
            <default ref="anyURI"/>
            <policy  ref="anyContent"/>
        </policyGroup>
		<policyGroup id="AnyContent">
		    <policy ref="antiSamy"/>
		    <policy  ref="anyURI"/>
		    <default ref="anyContent"/>
		</policyGroup>
		<policyGroup id="AntiSamyDefault">
		    <default ref="antiSamy"/>
		    <policy  ref="anyURI"/>
		    <policy  ref="anyContent"/>
		</policyGroup>
    </policyGroups>
    <policies>
		<!--
			Policy definitions.
		
			Ids ("id" attribute) should start with lower-case to distinguish
			them from policy groups (share the same namespace).
		
			The policy URI ("uri" attribute) is used to refer to the policy
			from outside the document (the id is only used within the document).
		
			The URI attribute can be any arbitrary URI, but should point
			to a resource located on a domain that is owned by the
			defining entity - these URIs are transmitted through
			import/export of tag-types, and should not clash with URIs
			of policies not under the defining entity's control.
		
			If a policy definition for a policy URI doesn't exist on a foreign
			system, a default policy will be used, which is usually more
			constraining than the actual policy definition. 

			It does not constitute an error, if a policy definition exist
			on a foreign system, that differs from the local definition with
			the same URI. (the policy definition on the foreign system will
			be used since policy definitions are not automatically transmitted
			through import/export, only the URI is).
			
			The URI must not be used for more than one unique policy definition
			at a time, and the purpose of the policy should be reflected in the
			URI.
			
			Additionally, the URI must not be longer than 255 characters.
			
			Other common settings:

			* id the XMLID that is used to refer to the policy withing this
			  document.

			* displayName the internationalization key. must be all lowercase.

			* policyFile the location of the AntiSamy policy file. If not
			  provided, the default AntiSamy policy file that is shipped with
			  the product will be used.
		-->
		<antiSamy id="antiSamy"
				  displayName="AntiSamy"
				  uri="http://www.gentics.com/validation/policy/antiSamy"
				  convertNodeTags="true"
				  policyFile="antisamy.custom.xml"
				  />
		<!-- 
			Will validate the input text in the context of the element and
			attribute defined with <occursIn ...>. This is useful to
			validate attribute values, which are not allowed to contain
			mixed content. 
		-->
        <attribute id="anyURI"
				   uri="http://www.gentics.com/validation/policy/anyURI"
				   displayName="validation.policies.anyuri"
				   policyFile="antisamy.custom.xml"
				   >
		  <occursIn element="a" attribute="href"/>
        </attribute>
		<!-- 
			Will not validate anything but will simply pass the input text
			through unchanged.
		-->        
        <passThrough id="anyContent"
					 uri="http://www.gentics.com/validation/policy/anyContent"
					 displayName="validation.policies.anycontent"
					 />
    </policies>
</policyMap>

=== gentics/cms-oss/cms-core/src/test/java/com/gentics/contentnode/tests/validation/map/policy-map.custom.xml
<policyMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="policy-map.xsd">
	<!-- Some random values for testing -->
	<inputChannels>
		<contentAdmin>
			<partTypes>
				<partType typeId="1234" ref="PolicyGroup"/>
				<default ref="PolicyGroup"/>
			</partTypes>
		</contentAdmin>
		<nodes>
			<default>
				<default ref="passThrough"/>
			</default>
		</nodes>
		<default ref="passThrough"/>
	</inputChannels>
    <policyGroups>
    	<policyGroup id="PolicyGroup">
    		<policy  ref="passThrough"/>
			<default ref="passThrough"/>
    	</policyGroup>
    </policyGroups>
	<policies>
		<passThrough id="passThrough" uri="http://example.com/passThrough"/>
    </policies>
</policyMap>

=== gentics/cms-oss/cms-core/src/test/java/com/gentics/contentnode/tests/validation/map/policy-map.minimal.xml
<policyMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="policy-map.xsd">
	<!-- The minimal structure that is required by the schema -->
	<inputChannels>
		<contentAdmin>
			<partTypes>
			</partTypes>
		</contentAdmin>
		<nodes>
			<default>
			</default>
		</nodes>
	</inputChannels>
    <policyGroups>
    </policyGroups>
	<policies>
    </policies>
</policyMap>

=== gentics/cms-oss/cms-core/src/main/java/com/gentics/contentnode/validation/map/policy-map.default.xml
<!-- 
	** Important Note **
	
	Customers may define their own policy-map. No incompatible changes to the
	schema schould be made (schema should only be extended) to avoid the customer's
	policy map to break. Any significant changes should be documented in the Gentics
	Content Node changelog.

	Also, there is an example policy-map documented in the infoportal (article about the
	"validation" feature) , which should be updated to reflect any changes made here.
	
	** Important Note **
	
	If any changes to the policies defined in the custom policy-map
	are made (in the policies section), the policy URI must be changed
	to a customer specific URI. Otherwise, there may be problems with
	Import/Export.
-->
<policyMap xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		   xsi:noNamespaceSchemaLocation="policy-map.xsd">
	<!--
		inputChannels map a channel through which data is being input
		into the system, to either a policy or policy-group (specified
		in the policy and policy-group sections).
	 -->
	<inputChannels>
		<contentAdmin>
			<!--
				Since the policy for part-types is configurable, they must
				refer to a policy-group and not directly to a policy. The
				policy-group specifies a number of policies that may be
				configured for a part-type.
			-->
			<partTypes>
				<!-- 
					URL part-types should only contain URIs. Never mixed content.
				-->
				<partType typeId="04" ref="AnyURI"/>   <!-- URL (page) -->
				<partType typeId="06" ref="AnyURI"/>   <!-- URL (image) -->
				<partType typeId="08" ref="AnyURI"/>   <!-- URL (file) -->
				<partType typeId="25" ref="AnyURI"/>   <!-- URL (folder) -->

				<!--
					Text parts, contrary to what their name indicates,
					don't escape HTML, and therefore need to be validated too
					(that's why commented-out).
			 	-->
				<!-- <partType typeId="01" ref="AnyContent"/> --><!-- Text -->
				<!-- <partType typeId="09" ref="AnyContent"/> --><!-- Text (short) -->

				<!--
					We allow mixed content by default since implementers have to
					be aware of the danger of using custom node tags
					in attributes. Editors will not be able to use node tags in
					attributes (unless a policy is configured that allows such
					usage, e.g. with the ignoreNodeTags option).
				-->
				<default ref="Paranoid"/>
			</partTypes>
		</contentAdmin>
		<nodes>
			<!--
				Policies for inputs associated with a node may be defined:
				<node localId="...">...</node>
			-->
			<!--
				The default configuration will be used, if no node-specific
				configuration exists.
			-->
			<default>
				<!--
					Example configuration for inputs associated with a
					particular node: 
					<folderDescription ref="paranoid"/>
					<folderName        ref="paranoid"/>
				-->
				<!--
					Node default policy - for all inputs associated with a
					node that don't have a policy configuration.
				-->
		  		<default ref="paranoid"/>
			</default>
		</nodes>
		<!--
			Global default policy - for all inputs that don't have a policy
			configuration.
		-->
		<default ref="paranoid"/>
	</inputChannels>
    <policyGroups>
		<!--
			Groups of policies. This is for configurable input channels.
			When displaying a tag-part definition of a tag-type, there,
			one can find a drop-down which reflects one of these groups.
			The <default> policy in each group will be used as the effective
			policy if none is configured by the user.
		-->
		<policyGroup id="Paranoid">
			<default ref="paranoid"/>
			<policy  ref="anyURI"/>
			<policy  ref="anyContent"/>
		</policyGroup>
		<policyGroup id="AnyURI">
			<policy  ref="paranoid"/>
            <default ref="anyURI"/>
            <policy  ref="anyContent"/>
        </policyGroup>
		<policyGroup id="AnyContent">
			<policy  ref="paranoid"/>
		    <policy  ref="anyURI"/>
		    <default ref="anyContent"/>
		</policyGroup>
    </policyGroups>
    <policies>
		<!--
			Policy definitions.
		
			Ids should start with lower-case to distinguish them from policy
			groups (share the same namespace).
		
			The policy URI is used to refer to the policy from outside the document
			(the id is only used within the document).
		
			The URI attribute can be any arbitrary URI, but should point
			to a resource located on a domain that is owned by the
			defining entity - these URIs are transmitted through
			import/export of tag-types, and should not clash with URIs
			of policies not under the defining entity's control.
		
			If a policy definition for a policy URI doesn't exist on a foreign
			system, a default policy will be used, which is usually more
			constraining than the actual policy definition. 

			It does not constitute an error, if a policy definition exist
			on a foreign system, that differs from the local definition with
			the same URI. (the policy definition on the foreign system will
			be used since policy definitions are not automatically transmitted
			through import/export, only the URI is).
			
			The URI must not be used for more than one unique policy definition
			at a time, and the purpose of the policy should be reflected in the
			URI.
			
			Additionally, the URI must not be longer than 255 characters.
			
			Other common settings:
			* id the XMLID that is used to refer to the policy withing this
			  document.
			* displayName the internationalization key. must be all lowercase.
		-->
		<!-- 
			The antiSamy policy uses AntiSamy for validation.
			
			* policyFile if provided, a relative or absolute URL to the AntiSamy
			  policy file. If not provided, the default policy file bundled with
			  the application is used.
			* domeMode defaults to false. It is not recommended to change this
			  default. AntiSamy provides two modes of operation, SAX mode and
			  DOM mode. DOM mode seems to be a little cleverer than SAX mode
			  but assumes HTML input and doesn't work with <node> tags.
			* outerElement defaults to <div>. Input text is always considered
			  a document fragment, that is, it may have multiple root nodes.
			  This option allows one, for the purpose of validation, to define
			  an outer element that provides a context node that the input text
			  is validated in. The default should not restrict the validation in
			  any way. 
		-->
        <antiSamy
        	id="paranoid"
        	displayName="validation.policies.paranoid"
        	uri="http://www.gentics.com/validation/policy/paranoid"
        	/>
		<!-- 
			The attribute policy will validate the input text in the context
			of the element and attribute defined with <occursIn ...>.
			This is useful to validate attribute values, which are not allowed
			to contain mixed content. 
			
			Uses AntiSamy for validation and as such inherits the antiSamy
			policy options with the exception of convertNodeTags,
			which is not implemented and will be ignored.
			
			* ignoreNodeTags true if node tags should be ignored, even
			  though this is an attribute value.
		-->
        <attribute
        	id="anyURI"
        	uri="http://www.gentics.com/validation/policy/anyURI"
		    displayName="validation.policies.anyuri"
            >
			<occursIn element="a" attribute="href"/>
        </attribute>
		<!-- 
			Will not validate anything but will simply pass the input text
			through unchanged.
		-->        
        <passThrough
        	id="anyContent"
        	uri="http://www.gentics.com/validation/policy/anyContent"
		    displayName="validation.policies.anycontent"
		    />
    </policies>
</policyMap>
